# Generated by Django 4.0.6 on 2022-07-17 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='decsription',
            new_name='description',
        ),
    ]
